let libreria = [
    {
        Titulo: "Cien Años de Soledad",
        Autor: "Gabriel García Márquez",
        Genero: "Realismo Mágico",
        Idioma: "Español",
        Formato: "Tapa Dura",
        ISBN: "978-0307474728",
        Descripcion: "Una de las obras más importantes de la literatura hispanoamericana.",
        Estado: "Nuevo",
        Ubicacion: "Estantería A1",
        Fecha_publicacion: "1967",
        Editorial: "Editorial Sudamericana",
        Paginas: "417",
        Dimensiones: "15.2 x 3.3 x 22.9 cm",
        Peso: "680 g"
    },
    {
        Titulo: "Don Quijote de la Mancha",
        Autor: "Miguel de Cervantes",
        Genero: "Novela",
        Idioma: "Español",
        Formato: "Tapa Blanda",
        ISBN: "978-8491050293",
        Descripcion: "La historia de un hidalgo que pierde la cordura por leer demasiadas novelas de caballería.",
        Estado: "Usado",
        Ubicacion: "Estantería B2",
        Fecha_publicacion: "1605",
        Editorial: "Alianza Editorial",
        Paginas: "1088",
        Dimensiones: "13 x 4.4 x 20.1 cm",
        Peso: "750 g"
    },
    {
        Titulo: "1984",
        Autor: "George Orwell",
        Genero: "Distopía",
        Idioma: "Inglés",
        Formato: "Tapa Blanda",
        ISBN: "978-0451524935",
        Descripcion: "Una novela que presenta una visión aterradora de una sociedad totalitaria.",
        Estado: "Nuevo",
        Ubicacion: "Estantería C3",
        Fecha_publicacion: "1949",
        Editorial: "Signet Classics",
        Paginas: "328",
        Dimensiones: "10.7 x 1.8 x 17.8 cm",
        Peso: "280 g"
    },{
        Titulo: "Orgullo y Prejuicio",
        Autor: "Jane Austen",
        Genero: "Romance",
        Idioma: "Inglés",
        Formato: "Tapa Dura",
        ISBN: "978-0141040349",
        Descripcion: "Una clásica novela de amor y malentendidos.",
        Estado: "Nuevo",
        Ubicacion: "Estantería D4",
        Fecha_publicacion: "1813",
        Editorial: "Penguin Classics",
        Paginas: "480",
        Dimensiones: "13.5 x 3 x 20.3 cm",
        Peso: "400 g"
    },
    {
        Titulo: "El Gran Gatsby",
        Autor: "F. Scott Fitzgerald",
        Genero: "Tragedia",
        Idioma: "Inglés",
        Formato: "Tapa Blanda",
        ISBN: "978-0743273565",
        Descripcion: "Una crítica a la era del jazz y el sueño americano.",
        Estado: "Nuevo",
        Ubicacion: "Estantería E5",
        Fecha_publicacion: "1925",
        Editorial: "Scribner",
        Paginas: "180",
        Dimensiones: "13.3 x 1.3 x 20.3 cm",
        Peso: "200 g"
    },
    {
        Titulo: "Matar a un Ruiseñor",
        Autor: "Harper Lee",
        Genero: "Ficción",
        Idioma: "Inglés",
        Formato: "Tapa Blanda",
        ISBN: "978-0060935467",
        Descripcion: "Una novela sobre la injusticia racial en el sur de los Estados Unidos.",
        Estado: "Usado",
        Ubicacion: "Estantería F6",
        Fecha_publicacion: "1960",
        Editorial: "Harper Perennial Modern Classics",
        Paginas: "336",
        Dimensiones: "13 x 1.9 x 19.7 cm",
        Peso: "300 g"
    },
    {
        Titulo: "Crimen y Castigo",
        Autor: "Fiódor Dostoyevski",
        Genero: "Filosófico",
        Idioma: "Ruso",
        Formato: "Tapa Dura",
        ISBN: "978-0140449136",
        Descripcion: "Una exploración profunda de la moralidad y el arrepentimiento.",
        Estado: "Nuevo",
        Ubicacion: "Estantería G7",
        Fecha_publicacion: "1866",
        Editorial: "Penguin Classics",
        Paginas: "671",
        Dimensiones: "12.9 x 4.1 x 19.8 cm",
        Peso: "500 g"
    },
    {
        Titulo: "Ulises",
        Autor: "James Joyce",
        Genero: "Modernismo",
        Idioma: "Inglés",
        Formato: "Tapa Blanda",
        ISBN: "978-0199535675",
        Descripcion: "Una de las obras más importantes de la literatura modernista.",
        Estado: "Nuevo",
        Ubicacion: "Estantería H8",
        Fecha_publicacion: "1922",
        Editorial: "Oxford University Press",
        Paginas: "933",
        Dimensiones: "13 x 5.1 x 19.3 cm",
        Peso: "700 g"
    },
    {
        Titulo: "El Proceso",
        Autor: "Franz Kafka",
        Genero: "Existencialismo",
        Idioma: "Alemán",
        Formato: "Tapa Blanda",
        ISBN: "978-0805209990",
        Descripcion: "Un retrato inquietante de la burocracia y la culpabilidad.",
        Estado: "Nuevo",
        Ubicacion: "Estantería I9",
        Fecha_publicacion: "1925",
        Editorial: "Schocken Books",
        Paginas: "304",
        Dimensiones: "13.3 x 1.9 x 20.3 cm",
        Peso: "290 g"
    },
    {
        Titulo: "La Odisea",
        Autor: "Homero",
        Genero: "Épica",
        Idioma: "Griego",
        Formato: "Tapa Blanda",
        ISBN: "978-0140268867",
        Descripcion: "La historia de las aventuras de Odiseo en su regreso a Ítaca.",
        Estado: "Nuevo",
        Ubicacion: "Estantería J10",
        Fecha_publicacion: "Siglo VIII a.C.",
        Editorial: "Penguin Classics",
        Paginas: "541",
        Dimensiones: "12.9 x 3.8 x 19.8 cm",
        Peso: "460 g"
    },
    {
        Titulo: "El Principito",
        Autor: "Antoine de Saint-Exupéry",
        Genero: "Fábula",
        Idioma: "Francés",
        Formato: "Tapa Dura",
        ISBN: "978-0156012195",
        Descripcion: "Una historia filosófica y poética sobre un joven príncipe.",
        Estado: "Nuevo",
        Ubicacion: "Estantería K11",
        Fecha_publicacion: "1943",
        Editorial: "Harcourt",
        Paginas: "96",
        Dimensiones: "18 x 1.3 x 22.9 cm",
        Peso: "300 g"
    },
    {
        Titulo: "En Busca del Tiempo Perdido",
        Autor: "Marcel Proust",
        Genero: "Modernismo",
        Idioma: "Francés",
        Formato: "Tapa Dura",
        ISBN: "978-0142437964",
        Descripcion: "Una extensa novela sobre la memoria y el tiempo.",
        Estado: "Nuevo",
        Ubicacion: "Estantería L12",
        Fecha_publicacion: "1913",
        Editorial: "Penguin Classics",
        Paginas: "4215",
        Dimensiones: "13 x 12.7 x 20.3 cm",
        Peso: "3200 g"
    },
    {
        Titulo: "El Señor de los Anillos",
        Autor: "J.R.R. Tolkien",
        Genero: "Fantasía",
        Idioma: "Inglés",
        Formato: "Tapa Dura",
        ISBN: "978-0544003415",
        Descripcion: "Una de las obras más influyentes de la literatura fantástica.",
        Estado: "Nuevo",
        Ubicacion: "Estantería M13",
        Fecha_publicacion: "1954",
        Editorial: "Houghton Mifflin Harcourt",
        Paginas: "1216",
        Dimensiones: "15.2 x 6.4 x 22.9 cm",
        Peso: "1600 g"
    },  {
        Titulo: "La Metamorfosis",
        Autor: "Franz Kafka",
        Genero: "Existencialismo",
        Idioma: "Alemán",
        Formato: "Tapa Blanda",
        ISBN: "978-0141045214",
        Descripcion: "La historia de Gregor Samsa, quien se despierta transformado en un insecto gigante.",
        Estado: "Nuevo",
        Ubicacion: "Estantería P16",
        Fecha_publicacion: "1915",
        Editorial: "Penguin Classics",
        Paginas: "224",
        Dimensiones: "13 x 1.5 x 20 cm",
        Peso: "250 g"
    },
    {
        Titulo: "El Guardián entre el Centeno",
        Autor: "J.D. Salinger",
        Genero: "Ficción",
        Idioma: "Inglés",
        Formato: "Tapa Blanda",
        ISBN: "978-0316769488",
        Descripcion: "La historia de Holden Caulfield, un adolescente rebelde que enfrenta una crisis emocional.",
        Estado: "Nuevo",
        Ubicacion: "Estantería Q17",
        Fecha_publicacion: "1951",
        Editorial: "Little, Brown and Company",
        Paginas: "277",
        Dimensiones: "13.3 x 2 x 20.3 cm",
        Peso: "300 g"
    },
    {
        Titulo: "La Isla del Tesoro",
        Autor: "Robert Louis Stevenson",
        Genero: "Aventura",
        Idioma: "Inglés",
        Formato: "Tapa Dura",
        ISBN: "978-0141321004",
        Descripcion: "Las aventuras del joven Jim Hawkins en su búsqueda de un tesoro pirata.",
        Estado: "Nuevo",
        Ubicacion: "Estantería R18",
        Fecha_publicacion: "1883",
        Editorial: "Penguin Classics",
        Paginas: "240",
        Dimensiones: "14.1 x 2 x 20.3 cm",
        Peso: "350 g"
    },
    {
        Titulo: "Drácula",
        Autor: "Bram Stoker",
        Genero: "Horror",
        Idioma: "Inglés",
        Formato: "Tapa Blanda",
        ISBN: "978-0141439846",
        Descripcion: "La historia del conde Drácula y su intento de mudarse desde Transilvania a Inglaterra.",
        Estado: "Nuevo",
        Ubicacion: "Estantería S19",
        Fecha_publicacion: "1897",
        Editorial: "Penguin Classics",
        Paginas: "488",
        Dimensiones: "13 x 2.5 x 19.8 cm",
        Peso: "400 g"
    },
    {
        Titulo: "Los Miserables",
        Autor: "Victor Hugo",
        Genero: "Drama",
        Idioma: "Francés",
        Formato: "Tapa Dura",
        ISBN: "978-0140444308",
        Descripcion: "Una novela épica sobre la injusticia social y la redención.",
        Estado: "Nuevo",
        Ubicacion: "Estantería T20",
        Fecha_publicacion: "1862",
        Editorial: "Penguin Classics",
        Paginas: "1232",
        Dimensiones: "13.7 x 5.5 x 20 cm",
        Peso: "980 g"
    },
    {
        Titulo: "El Nombre de la Rosa",
        Autor: "Umberto Eco",
        Genero: "Misterio",
        Idioma: "Italiano",
        Formato: "Tapa Blanda",
        ISBN: "978-0156001311",
        Descripcion: "Un misterio medieval sobre una serie de asesinatos en una abadía benedictina.",
        Estado: "Nuevo",
        Ubicacion: "Estantería U21",
        Fecha_publicacion: "1980",
        Editorial: "Harvest Books",
        Paginas: "536",
        Dimensiones: "15.2 x 3.2 x 22.9 cm",
        Peso: "620 g"
    },
    {
        Titulo: "El Retrato de Dorian Gray",
        Autor: "Oscar Wilde",
        Genero: "Ficción Gótica",
        Idioma: "Inglés",
        Formato: "Tapa Blanda",
        ISBN: "978-0141439570",
        Descripcion: "La historia de un joven que permanece eternamente joven mientras su retrato envejece.",
        Estado: "Nuevo",
        Ubicacion: "Estantería V22",
        Fecha_publicacion: "1890",
        Editorial: "Penguin Classics",
        Paginas: "254",
        Dimensiones: "13 x 1.5 x 19.8 cm",
        Peso: "300 g"
    }
];

let libro_nuevo= {
        Título: "To Kill a Mockingbird",
        Autor: "Harper Lee",
        Género: "Ficción",
        Idioma: "Inglés",
        Formato:" Tapa Dura",
        ISBN: "978-0060935467",
        Descripción:" Una novela clásica de la literatura estadounidense que explora temas de racismo y justicia en el sur de Estados Unidos.",
        Estado: "Usado",
        Ubicación:" Estantería A1",
        Fecha_publicacion: "1960",
        Editorial: "Harper Perennial Modern Classics",
        Páginas: "336",
        Dimensiones: "13.5 x 2.8 x 20.3 cm",
        Peso: "400 g"
    }

//agregar un libro
    /* libreria.push(libro_nuevo)
    console.log(libreria); */


//quitar un libro
/* ibreria.pop()
console.log(libreria);*/

//mostrar los libros

/* 
libreria.forEach((libro,index) =>{
    console.log(`${index +1} titulo : ${libro.Titulo}`);
})*/